### ISSUE TITLE
rakubrew.org certificate expired

### ISSUE THREAD

**Issue by SirBogman** [Raku/App-Rakubrew#12] opened 2020-05-18 14:27 UTC
The certificate for rakubrew.org expired a week ago and it makes it difficult to use.

**Comment by patrickbkr** [comment] 2020-05-20 14:09
This seems to be a duplicate of [Raku/rakubrew.org#5](https://github.com/Raku/rakubrew.org/issues/5) -> Closing.
 But thanks for the report anyways!

**Closed by patrickbkr** 2020-05-20 14:09 UTC
