### ISSUE TITLE
Variable "$self" will not stay shared at (re_eval 10) line 1

### ISSUE THREAD

**Issue by demanuel** [Raku/App-Rakubrew#46] opened 2022-02-09 12:01 UTC
- What's the output of `rakubrew rakubrew-version`?:

rakubrew v26 Build type: fatpack OS: linux

- Are you using rakubrew in `env` or in `shim` mode? (run `rakubrew mode` to find out):

env

- Where is rakubrew installed? (run `rakubrew home` to find out):

/home/demanuel/.rakubrew

When i do `rakubrew build moar master` to update my raku i get this warning:

> Variable "$self" will not stay shared at (re_eval 10) line 1.
> Variable "$last_text" will not stay shared at (re_eval 10) line 1.

I get these warning several times in the output. Example:

> Fetching submodule 3rdparty/nqp-configure
> ee232c02b0b817044bb2d3452eddad9d7ab83148
> Variable "$self" will not stay shared at (re_eval 10) line 1.
> Variable "$last_text" will not stay shared at (re_eval 10) line 1.
> ===ATTENTION===
>   No --prefix supplied, building and installing to /home/demanuel/.rakubrew/versions/moar-master/install
> Using /home/demanuel/.rakubrew/versions/moar-master/install/bin/nqp-m (version 2021.12-51-gaedc0e569 / MoarVM 2021.12-138-g280c709ce).
> Cleaning up ...
> +++ Checking for moar NQP version
> +++ Expanding   gen/moar/main-version.nqp
> Variable "$self" will not stay shared at (re_eval 10) line 1.
> Variable "$last_text" will not stay shared at (re_eval 10) line 1.
> +++ Generating  gen/moar/rakudo.nqp
> +++ Generating  gen/moar/Grammar.nqp
> +++ Generating  gen/moar/World.nqp
> +++ Generating  gen/moar/ModuleLoader.nqp
> +++ Compiling   blib/Perl6/ModuleLoader.moarvm
> +++ Generating  gen/moar/Ops.nqp
> +++ Compiling   dynext/libperl6_ops_moar.so
> +++ Compiling   blib/Perl6/Ops.moarvm
> +++ Generating  gen/moar/Pod.nqp
> +++ Compiling   blib/Perl6/Pod.moarvm
> +++ Compiling   blib/Perl6/World.moarvm
> +++ Generating  gen/moar/Actions.nqp
> +++ Compiling   blib/Perl6/Actions.moarvm
> +++ Compiling   blib/Perl6/Grammar.moarvm
> +++ Generating  gen/moar/Compiler.nqp
> +++ Generating  gen/moar/Optimizer.nqp
> +++ Generating  gen/moar/Metamodel.nqp
> +++ Compiling   blib/Perl6/Metamodel.moarvm
> +++ Compiling   blib/Perl6/Optimizer.moarvm
> +++ Compiling   blib/Perl6/Compiler.moarvm
> +++ Generating  gen/moar/SysConfig.nqp
> +++ Compiling   blib/Perl6/SysConfig.moarvm
> +++ Compiling   rakudo.moarvm
> +++ Generating  gen/moar/BOOTSTRAP/v6c.nqp
> +++ Compiling   blib/Perl6/BOOTSTRAP/v6c.moarvm
> Variable "$self" will not stay shared at (re_eval 10) line 1.
> Variable "$last_text" will not stay shared at (re_eval 10) line 1.
> 
> ....
> 
> +++ Generating  rakudo-gdb-m
> Variable "$self" will not stay shared at (re_eval 10) line 1.
> Variable "$last_text" will not stay shared at (re_eval 10) line 1.
> +++ Generating  rakudo-lldb-m
> Variable "$self" will not stay shared at (re_eval 10) line 1.
> Variable "$last_text" will not stay shared at (re_eval 10) line 1.
> +++ Generating  rakudo-valgrind-m
> Variable "$self" will not stay shared at (re_eval 10) line 1.
> Variable "$last_text" will not stay shared at (re_eval 10) line 1.
> +++ Generating  perl6-gdb-m
> Variable "$self" will not stay shared at (re_eval 10) line 1.
> Variable "$last_text" will not stay shared at (re_eval 10) line 1.
> +++ Generating  perl6-lldb-m
> Variable "$self" will not stay shared at (re_eval 10) line 1.
> Variable "$last_text" will not stay shared at (re_eval 10) line 1.
> +++ Generating  perl6-valgrind-m
> Variable "$self" will not stay shared at (re_eval 10) line 1.
> Variable "$last_text" will not stay shared at (re_eval 10) line 1.
> +++ Checking for moar NQP version
> +++ Creating installation directories
> +++ Removing old files
> +++ Installing files
> Variable "$self" will not stay shared at (re_eval 10) line 1.
> Variable "$last_text" will not stay shared at (re_eval 10) line 1.
> Variable "$self" will not stay shared at (re_eval 10) line 1.
> Variable "$last_text" will not stay shared at (re_eval 10) line 1.
> Variable "$self" will not stay shared at (re_eval 10) line 1.
> Variable "$last_text" will not stay shared at (re_eval 10) line 1.
> Variable "$self" will not stay shared at (re_eval 10) line 1.
> Variable "$last_text" will not stay shared at (re_eval 10) line 1.
> Variable "$self" will not stay shared at (re_eval 10) line 1.
> Variable "$last_text" will not stay shared at (re_eval 10) line 1.
> Variable "$self" will not stay shared at (re_eval 10) line 1.
> Variable "$last_text" will not stay shared at (re_eval 10) line 1.
> +++ Preparing installation
> 
> ....
> 

- Output of `uname` 

Linux #1 SMP Tue Nov 9 16:09:48 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

- Perl version:

perl-5.16.3

**Comment by patrickbkr** [comment] 2022-02-19 22:22
@vrurg: Can you make any sense of this? This seems to refer to [`3rdparty/nqp-configure/lib/NQP/Macros.pm:257`](https://github.com/Raku/nqp-configure/blob/9b98931e0bfb8c4aac61590edf5074e63aa8ea4b/lib/NQP/Macros.pm#L257). Is this something caused by the rather old Perl version?

**Comment by vrurg** [comment] 2022-02-20 01:10
Quick googling points into the same direction: a problem with older versions of Perl. @demanuel any chance to try with some less ancient Perl version?

I wonder if it still makes sense in maintaing 5.10.1 as the earliest supported release.

**Comment by demanuel** [comment] 2022-02-20 16:23
What's the minimum perl version required? The perl version i have installed is 5.16.3

**Comment by patrickbkr** [comment] 2022-02-20 17:44
I think the earliest we currently support is 5.10.1. So yes, the version 5.16.3 you are using is a supported version. To put things in context, the build does work. It's just that on older Perls a warning (unsure if legitimate) is thrown multiple times.

The question remains if a bump of supported version is in order, given that version 5.10 was released in 2007 and 5.16 was released in 2012.

@demanuel As a data point, how come the system you are using still has a Perl 5.16 installed?

**Comment by demanuel** [comment] 2022-02-20 17:48
@patrickbkr RHEL 7.9 :-)

RHEL 7.9 will be supported until June 30, 2024

**Comment by patrickbkr** [comment] 2022-02-20 17:51
OK. Then dropping support for 5.16 is not an option. Question then is, whether the warning is grave enough to do something about it. Opinions?

**Comment by demanuel** [comment] 2022-02-20 18:26
if rakubrew guarantees that the installation is good, i guess rakubrew could detect if the perl version is old and use perl -X or something similar.

**Comment by vrurg** [comment] 2022-02-20 23:18
In 2020 they release with Perl 5.16???? Oh, my... 

It seems, from what I found in the net, that the warning has always been considered rather incorrect. And it does look weird considering that nobody disable use of lexicals in a regexp code block.

What I'm not going to do is to re-write that regex. It took sufficiently much of my time and blood for me been reluctant to invest any more into it. Especially due to somebody in IBM considering it to be OK to use an 8 year old version of Perl.

Ideally if there is a `no warnings` pragma specific to this particular kind of issue. Then we can stick it into the module directly. But quick overview of the corresponding perl documentation page doesn't bring any appropriate one.

**Comment by patrickbkr** [comment] 2022-02-21 08:37
I think it's possible to do a `no warnings;` conditional on the Perl version. At least the manual of the [If module](https://metacpan.org/pod/if#no-if) suggests it's possible. So we could just disable all warnings on Perls 5.16 and older.

**Comment by patrickbkr** [comment] 2023-03-09 08:43
I'm closing this issue because I think it should be fixed in Rakudo and not Rakubrew should we decide to do something about it.

**Closed by patrickbkr** 2023-03-09 08:43 UTC
